services:
  server:
    container_name: digitalform-server
    build: 
      dockerfile: ./Dockerfile
    ports:
      # host:guest
      - 8080:8080
    secrets:
      - db-password
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db-password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - digitalform-network
    depends_on:
      - database
  database:
    image: 'postgres:13.1-alpine'
    container_name: digitalform-database
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - digitalform-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=form-db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
networks:
  digitalform-network:
