------------------------------------------------------------------------
-----------         TABLES         -------------------------------------
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS answer
(
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    answer text,
    fk_question bigint,
    fk_submission bigint
);

CREATE TABLE IF NOT EXISTS form
(
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description character varying(255),
    header character varying(255),
    published boolean,
    unlisted boolean,
    fk_user bigint
);

CREATE TABLE IF NOT EXISTS question
(
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    choices character varying(255)[],
    index integer,
    query character varying(255),
    required boolean NOT NULL,
    type character varying(255),
    fk_form bigint
);

CREATE TABLE IF NOT EXISTS submission
(
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_form bigint
);

CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) UNIQUE,
    name character varying(255),
    password character varying(255)
);

------------------------------------------------------------------------
-----------         CONSTRAINTS         --------------------------------
------------------------------------------------------------------------
DO
'
DECLARE
BEGIN
    -- add constraints
    ALTER TABLE IF EXISTS answer
        ADD CONSTRAINT fk_answer_question FOREIGN KEY (fk_question)
        REFERENCES question (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

    ALTER TABLE IF EXISTS answer
        ADD CONSTRAINT fk_answer_submission FOREIGN KEY (fk_submission)
        REFERENCES submission (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

    ALTER TABLE IF EXISTS form
        ADD CONSTRAINT fk_form_users FOREIGN KEY (fk_user)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

    ALTER TABLE IF EXISTS question
        ADD CONSTRAINT fk_question_form FOREIGN KEY (fk_form)
        REFERENCES form (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

    ALTER TABLE IF EXISTS submission
        ADD CONSTRAINT fk_submission_form FOREIGN KEY (fk_form)
        REFERENCES form (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;
    -- skip if constraints already exists
EXCEPTION
    WHEN duplicate_table THEN
    WHEN duplicate_object THEN
END;
'
LANGUAGE PLPGSQL;